### ISSUE TITLE
Allow to modify/create auth.conf

### ISSUE THREAD

**Issue by jnauska** [puppetlabs/puppetserver-helm-chart#101]
## Use Case
We're recreating our VM's all the time and as our VM's names don't change, the private key doesn't match the one stored in the puppetmaster.

While I could just exec in to the puppetmaster and execute `puppetserver node clean ${nodename}`, it breaks the automation as it is a manual step.

We need to be able to clean the private key remotely and as the auth.conf controls the puppet API access, we need to be able to modify/create it.

## Describe the Solution You Would Like
Allow modifications to the auth.conf file.

```
        {
            # Allow the CA CLI to access the certificate_status endpoint
            match-request: {
                path: "/puppet-ca/v1/certificate_status"
                type: path
                method: [get, put, delete]
            }
            allow-unauthenticated: true
            sort-order: 500
            name: "puppetlabs cert status"
        },
```

This modification allows unauthenticated access to the certificate endpoint in the puppetmaster.
As a result of this modifications I can introduce a shutdown-script which calls the API:

```
curl -XDELETE -H 'Accept: application/json text/pson' https://{puppetmaster}:8140/puppet-ca/v1/certificate_status/{nodename}
```

**Comment by Xtigyro** [comment]
Thanks for the proposition, @jnauska! Please feel free to send our way a PR - I'll be happy to review and merge it, afterwards. 🙇‍♂️

**Comment by davidphay** [comment]
Hello @jnauska seems this PR implement your request:  
https://github.com/puppetlabs/puppetserver-helm-chart/pull/125

Can you try it and tell us if it's ok ?

**Comment by davidphay** [comment]
Feel free to open it again if it's not solved.
