### ISSUE TITLE
Allow custom script to run 

### ISSUE THREAD

**Issue by bruno-lopes** [puppetlabs/puppetserver-helm-chart#131]
## Use Case
I need to run a custom script after the repository's synchronization. In my specific case, I need to create a Linux alias to an environment directory, so that I can have "fake environments" that point to the same code. But it could be anything else.

## Describe the Solution You Would Like
I would like to have a solution similar to custom entry points. So I can put the script in values.yaml file.

## Describe Alternatives You've Considered
I can't think about any other solution

## Additional Context
I'm preparing a PR with the solution.

**Comment by skoef** [comment]
Hi @bruno-lopes,

have you considered using r10k's `postrun` command? In the helm chart you can configure this by adding something like:
```yaml
r10k:
  ...
  code:
    ...
    extraSettings: ":postrun: ['/home/puppet/my_script.sh', '--environment', '$modifiedenvs']"
```

where `$modifiedenvs` is replaced with a space separated list of the environments that were just updated. In my setup I'm only using a single environment, so perhaps expanding these arguments would fail when you have multiple, but you get the hunch.

**Comment by davidphay** [comment]
Hi, @bruno-lopes, did you try it ? can you tell us if its ok ?

**Comment by davidphay** [comment]
If the solution doesn't fix you're problem please open it again, for now we close the issue without more information

**Comment by felipeatsix** [comment]
Hi @skoef I'm trying to use postrun as you suggested in the extraSettings but I'm not having success, could you please help me understand what I'm doing wrong?

## Context

In my puppet code I have a script "update-hiera.sh" with execute permissions to everyone.

Inside the script I run "sed" command to replace some placeholders with environment variables, these are for tokens and password fields.

When I run the script manually inside the r10k-code container the script works as expected.

## The problem

So I would expect my below configuration to execute the script just like I did in my manual test:
```
extraSettings: {":postrun: ['path/to/script/update-hiera.sh']"}
```
But when I go and check inside the container, nothing happened and the placeholders are not replaced.
I also don't get any logs of any failed script execution, it is like if nothing is triggered.

**Comment by felipeatsix** [comment]
@skoef 

Nevermind, I've noticed that in the r10k config file you're using ToYaml function, so I just used: 

```yaml
    extraSettings:
      postrun:
        - /path/to/myscript/update-hiera.sh
```

Now it works.
