### ISSUE TITLE
Unable to use puppet master server with LoadBalancer type

### ISSUE THREAD

**Issue by gmenuel** [puppetlabs/puppetserver-helm-chart#132]
## Describe the Bug
In PR #125 the option to change the service type for the puppetmaster service was removed, now it is always ClusterIP, thus if we are not using compilers the only usable option seems to be using an ingress in from of the puppetmaster. I think this was a mistake, and when compilers are not used the former behavior should be restored.

**Comment by davidphay** [comment]
Hey @gmenuel - thanks for the bug report!

It's a good point, please feel free to send our way a PR - I'll be happy to review and merge it, afterwards.
