### ISSUE TITLE
Doesn't start puppetserver after restart

### ISSUE THREAD

**Issue by akiryushin** [puppetlabs/puppetserver-helm-chart#155]
## Describe the Bug
After restart puppetserver pod doesn't run due to init-container 'perms-and-dirs'. 
check_for_masters.sh script has gone into an infinite loop. Also multimaster doesn't work.

## Expected Behavior
After restart puppetserver is running.

## Steps to Reproduce

1. helm repo add puppet https://puppetlabs.github.io/puppetserver-helm-chart
2. Create values.yaml
```
puppetserver:
    multiMasters:
         enabled: true
``` 
3. helm install --namespace puppetserver --name puppetserver puppet/puppetserver -f values.yaml
4. Restart puppetserver pod

## Environment
-  Kuberenets v1.19
- Helm v3.10.0
- puppetserver chart v7.2.2

## Additional Context
I propose two solutions to this problem:

1. Add a dynamic variable to [script](https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/templates/puppetserver-init-configmap.yaml#L14) as following `PUPPET_SSL_CERT_PEM="/etc/puppetlabs/puppet/ssl/certs/$(puppet config print certname).pem"`
2. Add environment variable to all configuration
```
 name: PUPPETSERVER_HOSTNAME
 value: puppet
```

**Comment by davidphay** [comment]
Hey @akiryushin - thanks for the bug report!

please feel free to send our way a PR - I'll be happy to review and merge it, afterwards.

**Comment by davidphay** [comment]
@akiryushin I prepare a PR for the fix

**Comment by davidphay** [comment]
Can you test now it should be fixed by this PR: https://github.com/puppetlabs/puppetserver-helm-chart/pull/159

**Comment by davidphay** [comment]
I close the issue, feel free to open it again if it not work as expected
