### ISSUE TITLE
runAsNonRoot

### ISSUE THREAD

**Issue by antwacky** [puppetlabs/puppetserver-helm-chart#161]
## Describe the Bug

The runAsNonRoot option does not appear to work. When enabling this option, the following error is seen on the pre-install hook `batch/Job/puppetserver-puppet-preinstall`:

```
Warning  FailedMount             61s (x8 over 2m4s)  kubelet                  MountVolume.SetUp failed for volume "r10k-code-volume" : configmap "puppetserver-r10k-code-config" not found
```

I assume this is because the configmap is not created until the preinstall hook has completed.

## Expected Behavior

The preinstall hook should complete successfully.

## Steps to Reproduce

Add the `runAsNonRoot` value to deploy the chart:

```
global:
  runAsNonRoot: true
```

## Environment
 - 7.4.0
 - K3s

## Additional Context
Nada

**Comment by davidphay** [comment]
Hi thnaks for the issue, weird I already use it an I have no issue, can you provide me the full values.yaml please ?

**Comment by davidphay** [comment]
Yes I am working on it, for now if you want continue, you can deploy r10k as container with `r10k.asSidecar: false` it should work.

**Comment by davidphay** [comment]
@pagey101 can you test the latest release please and tell me if the issue is fixed ?
https://github.com/puppetlabs/puppetserver-helm-chart/pull/162

**Comment by davidphay** [comment]
I close the issue, feel free to open it again if it not work as expected

**Comment by antwacky** [comment]
Apologies, I haven't got round to this yet! Thanks for the fix though.
