### ISSUE TITLE
7.4.1 changes break conf.d

### ISSUE THREAD

**Issue by justicel** [puppetlabs/puppetserver-helm-chart#164]
## Describe the Bug
Installing the 7.4.1 helm chart results in a broken installation. The conf.d folder is being destroyed by logic introduced in 7.4.1 for non-root.

## Expected Behavior
The conf.d folder to not be destroyed.

## Steps to Reproduce
- Install puppet with runAsNonRoot: false
- Look at logs of puppet-master. You should see errors about missing conf.d files.

The block specifically that needs to be re-worked is here: https://github.com/puppetlabs/puppetserver-helm-chart/blob/284f0eea1fc73cd424e44b7c429ca09e992b73ac/templates/puppetserver-deployment-masters.yaml#L283:L289

It shouldn't be mounting to the conf.d folder as this breaks any existing files in the folder when non-root.

**Comment by Xtigyro** [comment]
@davidphay Would you mind please checking this one?

**Comment by davidphay** [comment]
Hi, it should be good now, can you confirm ?

**Comment by justicel** [comment]
@davidphay Sorry, forgot to respond. It looks to be good now!

**Comment by Xtigyro** [comment]
Thank you, @davidphay!
