### ISSUE TITLE
docker image used for chart is dead

### ISSUE THREAD

**Issue by hadmut** [puppetlabs/puppetserver-helm-chart#179]
As far as I can see this chart makes use of the puppet/puppetserver , but this docker image is orphaned and not maintained or refreshed anymore. Even the code to generate the image has been removed from the puppetserver code and moved to 

https://github.com/puppetlabs-toy-chest/puppetserver-docker

Which also means that it is sort of security problem, if the image does not get security updates anymore.

**Comment by davidphay** [comment]
Hello,

I already forked the repository with the Dockerfile.
https://github.com/davidphay/puppetserver-docker
https://github.com/davidphay/puppetdb-docker

I build the image for puppet 8 but I didn't test it for now

**Comment by ldaneliukas** [comment]
IMHO we should use the images provided by [voxpupuli](https://github.com/voxpupuli) over at [voxpupuli/container-puppetserver](https://github.com/voxpupuli/container-puppetserver) and [voxpupuli/container-puppetdb](https://github.com/voxpupuli/container-puppetdb) as a reliable source. These have the latest versions of Puppetserver/PuppetDB 7 and have just started building Puppetserver/PuppetDB 8.
