### ISSUE TITLE
Cannot set custom CA DNS altname

### ISSUE THREAD

**Issue by qdii** [puppetlabs/puppetserver-helm-chart#182]
## Describe the Bug
There are two problems:
1. The helm chart currently sets the env variable DNS_ALT_NAMES to the value of `puppetserver.master.san`, however this field isn't documented in values.yaml
2. Furthermore, when setting this value, the DNS_ALT_NAMES environment variable doesn't seem to be populated correctly.

## Expected Behavior
The helm chart should allow the user to set the value of DNS_ALT_NAMES so that they can set a custom CA name.

## Steps to Reproduce
1. Install the helm chart by setting `puppetserver.master.san` to "foobar".
2. Use kubectl to describe the pod and notice that DNS_ALT_NAMES isn't correctly set.

**Comment by ldaneliukas** [comment]
Hi @qdii,

I think you misread the template. The value for `puppetserver.master.san` is not defined via `values.yaml` it is defined within the templates themselves from the value of `puppetserver.masters.fqdns.alternateServerNames` amongst a few others. I think you'll find that setting the following will give you the `DNS_ALT_NAMES` that you expect:

```yaml
puppetserver:
  masters:
    fqdns:
      alternateServerNames: "my-custom-san.here.com,second-one.here.com"
```

**Comment by qdii** [comment]
Ah you are totally right: here is the template from `_helpers.tpl`:

```
{{- define "puppetserver.master.san" -}}
{{- $san := printf "puppet,%s,%s" ( include "puppetserver.puppetserver.agents-to-masters.serviceName" . ) ( include "puppetserver.puppetserver-masters.serviceName" . ) -}}
{{- if and .Values.puppetserver.compilers.enabled (not .Values.singleCA.enabled) -}}
{{- $san = print $san "," ( include "puppetserver.puppetserver-compilers.serviceName" . ) -}}
{{- end -}}
{{- if .Values.puppetserver.masters.fqdns.alternateServerNames -}}
{{- $san = print $san "," .Values.puppetserver.masters.fqdns.alternateServerNames -}}
{{- end -}}
{{- if .Values.puppetserver.compilers.fqdns.alternateServerNames -}}
{{- $san = print $san "," .Values.puppetserver.compilers.fqdns.alternateServerNames -}}
{{- end -}}
{{- printf "%s" $san -}}
{{- end -}}
```
