### ISSUE TITLE
Install fails due to missing required variable in values.yaml

### ISSUE THREAD

**Issue by iscsrwm** [puppetlabs/puppetserver-helm-chart#186]
## Describe the Bug
r10k.code.readinessProbe is not defined in the default values.yaml file.  This prevents the chart from installing.  Either the doco should be updated to note this requirement or a default value should be added to the file.

## Expected Behavior
Installation to complete without errors.

## Steps to Reproduce
1. helm repo add puppet https://puppetlabs.github.io/puppetserver-helm-chart
2. help repo update
3. helm install --namespace puppetserver puppetserver puppet/puppetserver --set puppetserver.puppeturl='https://somerepo.com/control-repo.git'

## Environment
 - Version latest
 - Platform Kubernetes 1.26.7

## Additional Context
Error: INSTALLATION FAILED: Deployment.apps "puppetserver-puppetserver-master" is invalid: spec.template.spec.containers[1].readinessProbe.exec.command: Required value

**Comment by qdii** [comment]
I think this breaks the default installation of the helm chart for version 8.1.1. Could the PR be merged and a new version of the chart released?

**Comment by qdii** [comment]
A workaround is to set this in the helm chart:

```
r10k:
  code:
    readinessProbe:
      - /bin/true
```
