### ISSUE TITLE
values.yaml included in repo do not match artifacthub

### ISSUE THREAD

**Issue by vibe** [puppetlabs/puppetserver-helm-chart#196]
## Describe the Bug

Default values on ArtifactHub do not match the values.yaml in this repo. 

https://artifacthub.io/packages/helm/puppetserver/puppetserver

Specifically puppetserver.image and puppetdb.image including versions. 

## Expected Behavior
values.yaml should match

**Comment by Xtigyro** [comment]
@ldaneliukas Maybe something you can fix?

**Comment by davidphay** [comment]
It's fixed now, last time when I merged, I forget to run the workflow...

**Comment by Xtigyro** [comment]
Thank you!
