### ISSUE TITLE
r10k Deployment (non-sidecar) Permission Denied

### ISSUE THREAD

**Issue by ke5C2Fin** [puppetlabs/puppetserver-helm-chart#206]
Using puppetserver-helm-chart 9.1.0 with the r01k Deployment (non-sidecar) I was getting permissions denied on the r10k pod.

```
/bin/sh: /etc/puppetlabs/puppet/r10k_code_entrypoint.sh: Permission denied
```

I am unsure about the changes in [PR187](https://github.com/puppetlabs/puppetserver-helm-chart/pull/187) and if they relate.

I fixed this by editing https://github.com/puppetlabs/puppetserver-helm-chart/blob/master/templates/puppet-r10k-deployment.yaml `spec.template.spec.securityContext.fsGroup: {{ .Values.global.securityContext.runAsGroup }}`.

Maybe I should create a `.Values.global.securityContext.fsGroup` and use that instead?
If there is a preference then I will submit a PR.

**Comment by Xtigyro** [comment]
@ke5C2Fin Yes - please create `.Values.global.securityContext.fsGroup`. 

Thank you!
