### ISSUE TITLE
r10k_code_cronjob.sh and r10k_hiera_cronjob.sh might not be generated properly.

### ISSUE THREAD

**Issue by pjamenaja** [puppetlabs/puppetserver-helm-chart#70]
## Describe the Bug

By running the helm command below I think it generates the wrong "r10k_hiera_cronjob.sh" and "r10k_code_cronjob.sh"

> helm template --namespace puppetserver \
--name-template puppet-server-dev1 puppet/puppetserver \
--version v5.0.1 \
--set puppetserver.puppeturl=https://github.com/its-software-services-devops/temp-public.git \
--set hiera.hieradataurl=https://github.com/its-software-services-devops/temp-public.git 

If we take a look the generated ConfigMap "r10-hiera-config" we will see the snippet as show below. Please note that there is a "map[]" after --puppetfile and this cause the error when this script "r10k_hiera_cronjob.sh" executed, this also happen to r10k_code_cronjob.sh.

> r10k_hiera_cronjob.sh: |
    #!/usr/bin/env sh
    /docker-entrypoint.sh deploy environment --config /etc/puppetlabs/puppet/r10k_hiera.yaml \
    --puppetfile map[] > ~/.r10k_hiera_cronjob.out 2>&1
    retVal=$?
    if [ "$retVal" -eq "0" ]; then
      touch ~/.r10k_hiera_cronjob.success > /dev/null 2>&1
    else
      rm ~/.r10k_hiera_cronjob.success > /dev/null 2>&1
    fi
    exit $retVal

## Expected Behavior
There should not be "map[]" in the script.

## Steps to Reproduce
Run the command below and find the text "map[]" 

> helm template --namespace puppetserver \
--name-template puppet-server-dev1 puppet/puppetserver \
--version v5.0.1 \
--set puppetserver.puppeturl=https://github.com/its-software-services-devops/temp-public.git \
--set hiera.hieradataurl=https://github.com/its-software-services-devops/temp-public.git

**Comment by Xtigyro** [comment]
Thanks for the bug report, @pjamenaja! 

I've put a comment in your PR - some minor additions are required and should be good to go.

CC: @underscorgan @slconley @Iristyle @scottcressi @mwaggett @nwolfe @adrienthebo @dhollinger @binford2k @alannab
