### ISSUE TITLE
Error puppetboard - java.lang.Exception : No access from client <ip-address> allowed

### ISSUE THREAD

**Issue by pjamenaja** [puppetlabs/puppetserver-helm-chart#72]
## Describe the Bug
This bug related to the issue#566 here https://github.com/voxpupuli/puppetboard/issues/566. This cause the "Internal server 500" display when click the "Metrics" menu of puppetboard.

## Expected Behavior
Metrics should be show correctly.

## Steps to Reproduce
Please see - https://github.com/voxpupuli/puppetboard/issues/566 for the details.

## Environment
 - Version v5.0.1

I will submit another PR for fixing this issue.

**Comment by Xtigyro** [comment]
Thanks for the bug report, @pjamenaja!

I've put a few comments in the respective PR of yours - some changes are required.

CC: @underscorgan @slconley @Iristyle @scottcressi @mwaggett @nwolfe @adrienthebo @dhollinger @binford2k @alannab
