### ISSUE TITLE
Configurable accessModes for persistence

### ISSUE THREAD

**Issue by jstewart612** [puppetlabs/puppetserver-helm-chart#80]
## Use Case
Hard-coded ReadWriteOnce accessModes make HPA scaling impossible, despite its inclusion in this chart.

## Describe the Solution You Would Like
Make it configurable.

## Describe Alternatives You've Considered
The way it works today: which is it doesn't if you want to use HPAs.

## Additional Context
None needed.

**Comment by Xtigyro** [comment]
Hey @jstewart612 👋 

In which cloud provider you've tried and could you please also paste your user-defined Helm values?
