### ISSUE TITLE
Allow use of existing PVCs for persistence

### ISSUE THREAD

**Issue by jstewart612** [puppetlabs/puppetserver-helm-chart#81]
## Use Case
I don't want your chart managing my custom PVCs.

## Describe the Solution You Would Like
Allow use of existing PVCs for persistence.

## Describe Alternatives You've Considered
None exist in this chart.

## Additional Context
I hit this while trying to HPA scale and it failing.

**Comment by Xtigyro** [comment]
Thanks for the proposition, @jstewart612! Please feel free to send our way a PR - I'll be happy to review and merge it, afterwards. 🙇‍♂️

**Comment by davidphay** [comment]
@Xtigyro I think this feature is implemented now ?

```yaml
puppetserver.masters.customPersistentVolumeClaim
```

personally, I use HPA and I don't have any issue, I use custom PVC for puppet master (but not for the compiler, not implemented but not sure if it's necessary)

**Comment by Xtigyro** [comment]
@davidphay Yeah - it is. We can close this one.
