### ISSUE TITLE
r10k credentials for https

### ISSUE THREAD

**Issue by slconley** [puppetlabs/puppetserver-helm-chart#9]
From what I can tell, r10k configuration does not support using authenticated https for repo access.  It's not clear to me how the https credentials in these charts actually get used.  I think they would be disregarded in the r10k.yaml file.  Is this possibly carry-over from when git-sync was being used for repo access?

**Comment by Xtigyro** [comment]
@slconley Thanks for filing the issue! Appreciated!

You can pass creds for HTTPS authentication but it needs fixing. Issue confirmed.

**Comment by slconley** [comment]
In my current PR#2 I was pulling out https auth stuff...  I will revert some things to bring it back in.  I think it will still need changes based on other things I was doing.  I have marked that PR as WIP for now but will get all that sorted soon.

**Comment by Xtigyro** [comment]
I'm a bit undecided whether we should try to fix it or deprecate it. For now I'm more towards deprecating it.

**Comment by slconley** [comment]
I wish I had noticed your last comment sooner.  I did bring it all back and it wasn't too difficult.  It did help me uncover another issue I didn't realize I was having, related to existingSecret elements.

**Comment by Xtigyro** [comment]
Yeah - let's discuss stuff and then act, will be more pleasant and efficient. 
I'm gonna think today about the HTTPS Auth and let you know what's my stand on it, you can do the same - and we'll sync up.

**Comment by slconley** [comment]
From my research, the repo types that r10k supports are Git and SVN.  The natural transport for authenticated Git is SSH with private key.  SVN does use username/password but would be configured differently than how we are setting up https.  I think a direct https auth implementation would get pretty limited use.  My thinking would be to leave it out for now, which would be pretty easy for me to do.  As a quick side-note, I am still not clear on indentation guidelines for flow-control statements in templates.  Not sure if you would like to discuss here, but I do need clarification on that.

**Comment by Xtigyro** [comment]
> 
> 
> From my research, the repo types that r10k supports are Git and SVN. The natural transport for authenticated Git is SSH with private key. SVN does use username/password but would be configured differently than how we are setting up https. I think a direct https auth implementation would get pretty limited use. My thinking would be to leave it out for now, which would be pretty easy for me to do. As a quick side-note, I am still not clear on indentation guidelines for flow-control statements in templates. Not sure if you would like to discuss here, but I do need clarification on that.

We can chat on the Puppet Community Slack workspace: https://slack.puppet.com/
You can find me there: `Miro Hadzhiev`.

**Comment by Xtigyro** [comment]
Fixed by https://github.com/Xtigyro/puppetserver-helm-chart/pull/13.
