### ISSUE TITLE
Puppet Report Prometheus Exporter Support

### ISSUE THREAD

**Issue by asreich** [puppetlabs/puppetserver-helm-chart#92]
## Use Case
I'd like to be able to leverage https://github.com/voxpupuli/puppet-prometheus_reporter to put some of the data from Puppetboard report parsing into Prometheus/Grafana so we can report/alert on it.

## Describe the Solution You Would Like
I'd like the puppetserver Helm Chart to support this exporter natively so I could just turn this on/off.

## Describe Alternatives You've Considered
I've thought about adding the node_exporter as an extra container and see that I should be able to configure the reports settings by using some environment variables (thanks to the docker-entrypoint.d scripts), but I'm failing to understand how I'm supposed to get this module into one of these images to be able to get the reports written in the first place.

## Additional Context
This may require modifying the puppetserver images? But maybe y'all are more familiar of the various was to set it up.

**Comment by Xtigyro** [comment]
Thanks for the proposition, @asreich! Please feel free to send our way a PR - I'll be happy to review and merge it, afterwards. 🙇‍♂️

**Comment by davidphay** [comment]
I currently implement this exporter: https://github.com/camptocamp/prometheus-puppetdb-exporter

It's not totally the same but it's easier to implement.

If it's not enough fell free to implement this one !

**Comment by ashish1099** [comment]
It would be nice to have this

**Comment by ashish1099** [comment]
I have added a fix for this, if someone is interested to look at it.

* Added a deployment [here](https://github.com/Obmondo/kubeaid/blob/master/argocd-helm-charts/puppetserver/templates/puppet-agent-exporter.yaml)
* Created a small go project, which will read all the prom file and generates a metrics (which prom can scrape)

```
puppetAgentExporter:
  image: ghcr.io/obmondo/dockerfiles/puppet-agent-exporter
  tag: v0.0.1
  imagePullPolicy: IfNotPresent
  extraEnv:
    METRICS_PATH: /etc/puppetlabs/code/prometheus-dropzone
  resources:
    limits:
      memory: 50Mi
    requests:
      memory: 50Mi
      cpu: 20m
     
puppetserver:
  global: {}
  puppetserver:
    puppeturl: "https://github.com/Obmondo/LinuxAid.git"
    image: ghcr.io/voxpupuli/container-puppetserver
    tag: 7.17.0-v1.5.0
    customentrypoints:
      enabled: true
      configmaps:
        configure_external_nodes.sh: |-
          #!/bin/bash

          set -e
          # Configure puppet to use a certificate autosign script (if it exists)
          # AUTOSIGN=true|false|path_to_autosign.conf
          if test -n "${PUPPETSERVER_ENC_PATH}" ; then
            puppet config set external_nodes "$PUPPETSERVER_ENC_PATH" --section server
            puppet config set node_terminus "exec" --section server
          fi

          puppet config set reports "puppetdb,prometheus" --section server
          puppetserver gem install fugit -v 1.9.0
          puppetserver gem install tzinfo-data

          cat <<EOL > "/etc/puppetlabs/puppet/prometheus.yaml"
          ---
          textfile_directory: /etc/puppetlabs/code/prometheus-dropzone
          environments:
            - master
          stale_time: 30
          EOL

          mkdir -p /etc/puppetlabs/code/prometheus-dropzone
          chown puppet:puppet /etc/puppetlabs/code/prometheus-dropzone

```
